import { Card } from "@/components/ui/card";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Heart, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { formatDistanceToNow } from "date-fns";
import { fr } from "date-fns/locale";
import { motion } from "framer-motion";
import type { GratitudeMessage as GratitudeMessageType } from "@/hooks/useGratitudeWall";

interface GratitudeMessageProps {
  message: GratitudeMessageType;
  onAddReaction: (messageId: string) => void;
}

export const GratitudeMessage = ({ message, onAddReaction }: GratitudeMessageProps) => {
  const isAutoGenerated = message.message_type === 'auto';
  
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
    >
      <Card className="p-4 backdrop-blur-sm border border-border/50 bg-gradient-to-br from-primary/5 to-secondary/5">
        <div className="flex items-start gap-3">
          <Avatar className="h-12 w-12 border-2 border-primary/20">
            <AvatarImage src={message.contributor_avatar} />
            <AvatarFallback className="bg-primary/10 text-primary">
              {message.contributor_name?.[0]?.toUpperCase() || '?'}
            </AvatarFallback>
          </Avatar>

          <div className="flex-1 space-y-2">
            <div className="flex items-center gap-2">
              <span className="font-semibold text-sm text-foreground">
                {message.contributor_name}
              </span>
              {isAutoGenerated && (
                <Badge variant="secondary" className="text-xs gap-1">
                  <Sparkles className="h-3 w-3" />
                  Auto
                </Badge>
              )}
              <span className="text-xs text-muted-foreground">
                {formatDistanceToNow(new Date(message.created_at), {
                  addSuffix: true,
                  locale: fr
                })}
              </span>
            </div>

            <p className="text-sm text-foreground/90 leading-relaxed">
              {message.message_text}
            </p>

            <div className="flex items-center gap-2 pt-1">
              <Button
                variant="ghost"
                size="sm"
                className="h-8 gap-2 text-muted-foreground hover:text-primary"
                onClick={() => onAddReaction(message.id)}
              >
                <Heart className="h-4 w-4" />
                <span className="text-xs font-medium">{message.reaction_count}</span>
              </Button>
            </div>
          </div>
        </div>
      </Card>
    </motion.div>
  );
};
